version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-photographer
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: